# This file was generated by GoReleaser. DO NOT EDIT.
cask "tycana" do
  name "tycana"
  desc "Terminal-first task manager with calendar sync"
  homepage "https://tycana.com"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tycana"

  on_macos do
    on_intel do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_darwin_x86_64.tar.gz"
      sha256 "1951654ccd53486711ff89a4ccf0ac5020a8ed85fb7311caaa524a164f2193f5"
    end
    on_arm do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_darwin_arm64.tar.gz"
      sha256 "d334a3cabe823ce92e4de43274d7e11150883b57dfcd970617356069948680af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_linux_x86_64.tar.gz"
      sha256 "6609d14743a0d4948e18803b36342bb71e285c1e16de22b29e2f1a2fc92ba685"
    end
    on_arm do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_linux_arm64.tar.gz"
      sha256 "434044c3e1cb01e14729694ca930aeaafa50548a5bd9a3ce71c37527601bda26"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tycana"]
    end
  end

  # No zap stanza required
end
