# This file was generated by GoReleaser. DO NOT EDIT.
cask "tycana" do
  name "tycana"
  desc "Terminal-first task manager with calendar sync"
  homepage "https://tycana.com"
  version "0.2.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tycana"

  on_macos do
    on_intel do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_darwin_x86_64.tar.gz"
      sha256 "8cc83bb4bb503c5d82300907ccafe36610292a465028737bba08005ee7c71d40"
    end
    on_arm do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_darwin_arm64.tar.gz"
      sha256 "a967f99cbcef5d12f6d5bf1c3d7ae46c310c7bb35a13d0389d8f0c100425dac6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_linux_x86_64.tar.gz"
      sha256 "ef947d049e6fd1694d4cabf0c41b58b26f5b27d90989ba37144c2190c57fa024"
    end
    on_arm do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_linux_arm64.tar.gz"
      sha256 "517ee828146961d321a123eb41631e2114b4c8133f89eed2f0865bc610a50e8b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tycana"]
    end
  end

  # No zap stanza required
end
