# This file was generated by GoReleaser. DO NOT EDIT.
cask "tycana" do
  name "tycana"
  desc "Terminal-first task manager with calendar sync"
  homepage "https://tycana.com"
  version "0.2.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tycana"

  on_macos do
    on_intel do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_darwin_x86_64.tar.gz"
      sha256 "aa2796d73de2197a85f3eca0433d0f76a3e662829d2655c6667093142f643219"
    end
    on_arm do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_darwin_arm64.tar.gz"
      sha256 "a8da6a97c64d966bcd3ef58942916c7b3a2c364c86d6193b0e4e14d5612a2e3a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_linux_x86_64.tar.gz"
      sha256 "2ac5490fbe16d812b03974fbecc9962020229c30b685b92929d0daedd4907096"
    end
    on_arm do
      url "https://github.com/tycana/releases/releases/download/v#{version}/tycana_#{version}_linux_arm64.tar.gz"
      sha256 "9d8043cc40a60c3c0f930693f4492cbe01cb8b373e1ee338f68b6620afc52813"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tycana"]
    end
  end

  # No zap stanza required
end
